name: Run Tests on Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Go to test directory
      working-directory: ./pokemon-backend
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
